/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as PeliculasRouteImport } from './routes/peliculas'
import { Route as MiListaRouteImport } from './routes/mi-lista'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContenidoIdRouteImport } from './routes/contenido.$id'

const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const PeliculasRoute = PeliculasRouteImport.update({
  id: '/peliculas',
  path: '/peliculas',
  getParentRoute: () => rootRouteImport,
} as any)
const MiListaRoute = MiListaRouteImport.update({
  id: '/mi-lista',
  path: '/mi-lista',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContenidoIdRoute = ContenidoIdRouteImport.update({
  id: '/contenido/$id',
  path: '/contenido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/buscar': typeof BuscarRoute
  '/mi-lista': typeof MiListaRoute
  '/peliculas': typeof PeliculasRoute
  '/series': typeof SeriesRoute
  '/contenido/$id': typeof ContenidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/buscar': typeof BuscarRoute
  '/mi-lista': typeof MiListaRoute
  '/peliculas': typeof PeliculasRoute
  '/series': typeof SeriesRoute
  '/contenido/$id': typeof ContenidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/buscar': typeof BuscarRoute
  '/mi-lista': typeof MiListaRoute
  '/peliculas': typeof PeliculasRoute
  '/series': typeof SeriesRoute
  '/contenido/$id': typeof ContenidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/buscar'
    | '/mi-lista'
    | '/peliculas'
    | '/series'
    | '/contenido/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/buscar'
    | '/mi-lista'
    | '/peliculas'
    | '/series'
    | '/contenido/$id'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/buscar'
    | '/mi-lista'
    | '/peliculas'
    | '/series'
    | '/contenido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  BuscarRoute: typeof BuscarRoute
  MiListaRoute: typeof MiListaRoute
  PeliculasRoute: typeof PeliculasRoute
  SeriesRoute: typeof SeriesRoute
  ContenidoIdRoute: typeof ContenidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peliculas': {
      id: '/peliculas'
      path: '/peliculas'
      fullPath: '/peliculas'
      preLoaderRoute: typeof PeliculasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-lista': {
      id: '/mi-lista'
      path: '/mi-lista'
      fullPath: '/mi-lista'
      preLoaderRoute: typeof MiListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contenido/$id': {
      id: '/contenido/$id'
      path: '/contenido/$id'
      fullPath: '/contenido/$id'
      preLoaderRoute: typeof ContenidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  BuscarRoute: BuscarRoute,
  MiListaRoute: MiListaRoute,
  PeliculasRoute: PeliculasRoute,
  SeriesRoute: SeriesRoute,
  ContenidoIdRoute: ContenidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
